### ISSUE TITLE
[Bug] Documentation navbar incorrect

### ISSUE THREAD

**Issue by MichaelZhao21** [hackutd/jury#109]
### What Happened?

Navbar says "contributing" when it really should say "Setup"

### Steps to Reproduce

1. Go to https://jury.mikz.dev
2. Click "Contributing" on navbar

**Comment by pranay911** [comment]
Hey @MichaelZhao21  Can you please assign this issue to me?

**Comment by MichaelZhao21** [comment]
not needed
