### ISSUE TITLE
[Bug] Judge ranking system does not work on some devices

### ISSUE THREAD

**Issue by abdullah50053** [hackutd/jury#150]
### What Happened?

A judge was trying to order their rankings and was unable to do so because of how the UI is set up.

### Steps to Reproduce

1. Add judges and projects
2. Finish judging a few projects
3. Rank projects

### What device(s) are you seeing this issue on?

Android Mobile Device, iOS Mobile Device

### Possible Solutions

Instead of having to use just the hamburger menu to move cards up or down for rankings, make the entire card sensitive to reorder. An alternative solution could be to add arrows for the ranking system.

**Comment by MichaelZhao21** [comment]
what does this mean?? the issue with having entire card draggable is that mobile devices you can't scroll. arrows get too small i feel like, but could be a solution if this isn't working. Is there a specific mobile browser this problem is on?
