### ISSUE TITLE
[Bug] Add focus color to buttons

### ISSUE THREAD

**Issue by MichaelZhao21** [hackutd/jury#174]
### What Happened?

Buttons have no visible focus color; this is bad for accessibility. There are a lot of buttons on the admin dashboard, especially the settings page and would cause issues if you are tabbing through the settings.

### Steps to Reproduce

1. Go to the home page
2. Try to tab to buttons
3. Oh you can't see womp womp

### Possible Solutions

Change it to the same color as the hover or add a different border or smth.

**Comment by zaheer-Khan3260** [comment]
Can you provide the Screen shot of the problem that you facing and I can fix this issue.

**Comment by Jeevan-Neupane** [comment]
Assign this to me . I want to work on it.

**Comment by MichaelZhao21** [comment]
Closing this issue temporarily due to major changes being made for #167
