### ISSUE TITLE
[Bug] Judge stats should update on judge add

### ISSUE THREAD

**Issue by MichaelZhao21** [hackutd/jury#176]
### What Happened?

![image](https://github.com/user-attachments/assets/1357de7d-e44a-448c-89eb-f5bbed8bbc8e)

These don't update when you add a judge. We should refresh the stats whenever we finish updating a judge.

### Steps to Reproduce

1. Log into the admin dashboard
2. Go to Judge tab > Add Judges
3. Add a judge
4. The numbers don't change!

### Possible Solutions

Simply call the get judge stats api endpoint to refresh the stats.

**Comment by zaheer-Khan3260** [comment]
Hey @MichaelZhao21 i love to work on this issue please assign it to me.

**Comment by MichaelZhao21** [comment]
@zaheer-Khan3260 status on this?

**Comment by zaheer-Khan3260** [comment]
I try to set this project into my local enviroment but for backend it ask for env file and in env it's ask for sender email name and sendgridapikey i try to get a sendgrid api key but for some reason it didn't allow me to login i think is there some bugs in the sendgrid website so i am not able to start the backen if you provide me your links then i am able to start the backend and fix this issue.

**Comment by MichaelZhao21** [comment]
@zaheer-Khan3260 this is not a backend issue. You can use the staging backend and only run the frontend locally. Follow these instructions: https://jury.mikz.dev/docs/contributing#only-running-frontend
