### ISSUE TITLE
Clean up admin index.tsx

### ISSUE THREAD

**Issue by MichaelZhao21** [hackutd/jury#191]
### Describe the feature you'd like

![image](https://github.com/user-attachments/assets/e567c846-7efa-45ef-993f-a79ab1d461da)

This part should be extracted to a component called AdminHeader or smth similar. The above code + its related functionality can live in its own component and makes the index page of admin clean again.

**Comment by TranMinhQuangB2111946** [comment]
Can I do this? @MichaelZhao21

**Comment by MichaelZhao21** [comment]
@TranMinhQuangB2111946 assigned

**Comment by TranMinhQuangB2111946** [comment]
Can you check the pull request for me if it ok can you merge it?. Thank you so much.
