### ISSUE TITLE
Use bulkWrite for updateJudges instead of a transaction

### ISSUE THREAD

**Issue by MichaelZhao21** [hackutd/jury#192]
### Describe the feature you'd like

See `updateProjects` function for bulkWrite usage. I used a transaction to write to all judge documents at once, but bulkWrite is better.

**Comment by samrat-rm** [comment]
Hi @MichaelZhao21 , I’ve reviewed the changes required and am ready to take this on. Could you please assign the PR to me? Thanks!

**Comment by samrat-rm** [comment]
@MichaelZhao21  Please review this 

https://github.com/hackutd/jury/pull/216

**Comment by MichaelZhao21** [comment]
Completed by #216
