### ISSUE TITLE
Alert Text

### ISSUE THREAD

**Issue by zaheer-Khan3260** [hackutd/jury#199]
### Describe the feature you'd like

I want to add a custom message component. So, instead of showing alert which can block all the flow it simple show a popup message. like Judge is deleted or judge successfully added.

### Pre-existing Issue or Justification

The alert panel is so frustated because it doesn't allow to go further util we click on the ok button

### Additional context

I can add this feature. so please assign it to me.

**Comment by MichaelZhao21** [comment]
This is already being worked on in #100

**Comment by zaheer-Khan3260** [comment]
but as i see now when i delete or add judge then the browser alert is open and it's not looking good at all
