### ISSUE TITLE
[Bug] Spacing under name is weird fro general track judging

### ISSUE THREAD

**Issue by MichaelZhao21** [hackutd/jury#210]
### What Happened?

![image](https://github.com/user-attachments/assets/3fe6dcda-31ab-45bf-818d-03e705c10416)

If the judge is judging a track, there would be text under the name with the track. Unfortunately, without the track, there is no good padding. We should've added margins to the button underneath instead.

### Steps to Reproduce

1. Go to judging page (log in as a judge)
2. See the page

### Possible Solutions

Add margin to top of button instead of track text

**Comment by yuriBaza23** [comment]
Hello, I would like to work on this issue

**Comment by MichaelZhao21** [comment]
Resolved by #218
